import { NextRequest, NextResponse } from "next/server";
import OpenAI from "openai";

const openai = new OpenAI({
  baseURL: "https://openrouter.ai/api/v1",
  apiKey: process.env.OPENROUTER_API_KEY,
});

// The three stages that have a Generative UI widget, IN THE ORDER
// they must appear. "final" is intentionally separate — it only fires
// once all 7 fields (including the 3 below) have been collected.
const UI_SEQUENCE = ["groupsize", "budget", "tripduration"] as const;
type UiStage = (typeof UI_SEQUENCE)[number] | "final" | "";

const PROMPT = `You are an AI Trip Planner Agent. Your goal is to help the user plan a trip by asking one relevant trip-related question at a time.

Only ask questions about the following details in this exact order, and wait for the user's answer before asking the next:

1. Starting location (source)
2. Destination city or country
3. Group size (Solo, Couple, Family, Friends)
4. Budget (Low, Medium, High)
5. Trip duration (number of days)
6. Travel interests (e.g., adventure, sightseeing, cultural, food, nightlife, relaxation)
7. Special requirements or preferences (if any)

Do not ask multiple questions at once, and never ask irrelevant questions. Do not re-summarize or restate previously collected answers (e.g. don't say "since it's a family trip with a moderate budget...") — just ask the next question plainly, since restating earlier answers can confuse the UI that displays alongside your response.

If any answer is missing or unclear, politely ask the user to clarify before proceeding.

Always maintain a conversational, interactive style while asking questions.

CRITICAL — RESPONSE FORMAT: On every single turn, with no exceptions, respond ONLY with a strict JSON object (no markdown fences, no extra text) matching this schema:

{
  "resp": "Text response / question shown to the user",
  "ui": "groupSize" | "budget" | "tripDuration" | "final" | ""
}

Rules for the "ui" field:
- Use "groupSize" ONLY on the turn where you ask about group size.
- Use "budget" ONLY on the turn where you ask about budget.
- Use "tripDuration" ONLY on the turn where you ask about trip duration.
- Use "" (empty string) for every other question (source, destination, interests, special requirements).
- Use "final" ONLY once all 7 fields have been collected, when you are presenting/generating the complete trip plan.
- Never reuse "groupSize", "budget", or "tripDuration" more than once in the whole conversation.`;

const FINAL_PROMPT = `Generate Travel Plan with give details, give me Hotels options list with HotelName, 

Hotel address, Price, hotel image url, geo coordinates, rating, descriptions and  suggest itinerary with placeName, Place Details, Place Image Url,

 Geo Coordinates,Place address, ticket Pricing, Time travel each of the location , with each day plan with best time to visit in JSON format.

 Output Schema:

 {

  "trip_plan": {

    "destination": "string",

    "duration": "string",

    "origin": "string",

    "budget": "string",

    "group_size": "string",

    "hotels": [

      {

        "hotel_name": "string",

        "hotel_address": "string",

        "price_per_night": "string",

        "hotel_image_url": "string",

        "geo_coordinates": {

          "latitude": "number",

          "longitude": "number"

        },

        "rating": "number",

        "description": "string"

      }

    ],

    "itinerary": [

      {

        "day": "number",

        "day_plan": "string",

        "best_time_to_visit_day": "string",

        "activities": [

          {

            "place_name": "string",

            "place_details": "string",

            "place_image_url": "string",

            "geo_coordinates": {

              "latitude": "number",

              "longitude": "number"

            },

            "place_address": "string",

            "ticket_pricing": "string",

            "time_travel_each_location": "string",

            "best_time_to_visit": "string"

          }

        ]

      }

    ]

  }

}
`


export async function POST(req: NextRequest) {
  try {
    const { messages, isFinal } = await req.json();

    const completion = await openai.chat.completions.create({
      model: "openai/gpt-4o-mini",
      response_format: {
        type: "json_object",
      },
      messages: [
        {
          role: "system",
          content: isFinal ? FINAL_PROMPT : PROMPT,
        },
        ...messages,
      ],
    });

    const rawContent: unknown = completion?.choices?.[0]?.message?.content;

    if (!rawContent) {
      return NextResponse.json(
        {
          error: "No response generated by AI.",
        },
        {
          status: 500,
        }
      );
    }

    const normalizeUi = (value: unknown): UiStage | null => {
      if (typeof value !== "string") return null;
      const normalized = value.trim().toLowerCase().replace(/\s+/g, "");
      if (normalized === "groupsize") return "groupsize";
      if (normalized === "budget") return "budget";
      if (normalized === "tripduration") return "tripduration";
      if (normalized === "final") return "final";
      if (normalized === "") return "";
      return null;
    };

    // Fallback ONLY used if the model fails to return a valid "ui" value at all.
    // Checked in actual conversation order (not an arbitrary priority) and only
    // considers whichever stage hasn't been used yet, so it can't jump ahead
    // or re-trigger an earlier widget.
    const inferUiFromText = (text: string, nextExpected: UiStage) => {
      const lower = text.toLowerCase();
      if (/final|complete trip plan|here is your (trip )?plan|your trip plan is ready/.test(lower)) {
        return "final" as UiStage;
      }
      if (nextExpected === "groupsize" && /group size|solo|couple|family|friends/.test(lower)) {
        return "groupsize" as UiStage;
      }
      if (nextExpected === "budget" && /\bbudget\b/.test(lower)) {
        return "budget" as UiStage;
      }
      if (nextExpected === "tripduration" && /trip duration|how many days/.test(lower)) {
        return "tripduration" as UiStage;
      }
      return "" as UiStage;
    };

    let parsed: any = null;

    try {
      if (typeof rawContent === "string") {
        try {
          parsed = JSON.parse(rawContent);
        } catch (e) {
          parsed = { resp: rawContent };
        }
      } else if (Array.isArray(rawContent)) {
        const joined = (rawContent as any[])
          .map((c: any) => (typeof c === "string" ? c : c?.text ?? JSON.stringify(c)))
          .join("");
        try {
          parsed = JSON.parse(joined);
        } catch (e) {
          parsed = { resp: joined };
        }
      } else if (typeof rawContent === "object" && rawContent !== null) {
        const objContent = rawContent as Record<string, unknown>;
        if (typeof objContent.text === "string") {
          try {
            parsed = JSON.parse(objContent.text);
          } catch (e) {
            parsed = { resp: objContent.text, ui: objContent.ui ?? null };
          }
        } else {
          parsed = objContent;
        }
      } else {
        parsed = { resp: String(rawContent) };
      }
    } catch (e) {
      parsed = { resp: String(rawContent), error: "Failed to parse AI response", details: String(e) };
    }

    const respText = typeof parsed?.resp === "string" ? parsed.resp : String(parsed?.resp ?? "");

    // --- Deterministic ordering guard ---
    // Look at the ui field on every past assistant message already in the
    // conversation to figure out which of the 3 ordered widget stages have
    // already been shown, so we know what's allowed to come next.
    const alreadyUsedStages = new Set(
      (Array.isArray(messages) ? messages : [])
        .filter((m: any) => m?.role === "assistant" && typeof m?.ui === "string")
        .map((m: any) => m.ui.trim().toLowerCase().replace(/\s+/g, ""))
        .filter((ui: string) => (UI_SEQUENCE as readonly string[]).includes(ui))
    );
    const nextExpectedStage: UiStage =
      UI_SEQUENCE.find((stage) => !alreadyUsedStages.has(stage)) ?? "final";

    let uiValue = normalizeUi(parsed?.ui ?? parsed?.UI ?? "");
    if (uiValue === null) {
      // Model returned something unrecognized/missing — fall back to
      // conservative text inference restricted to the next expected stage.
      uiValue = inferUiFromText(respText, nextExpectedStage);
    } else if (
      (UI_SEQUENCE as readonly string[]).includes(uiValue) &&
      uiValue !== nextExpectedStage
    ) {
      // Model tried to show an out-of-order or repeated widget
      // (e.g. asked for "budget" again after it was already collected,
      // or jumped straight to "tripduration" before "budget").
      // Correct it to the widget that's actually next in sequence.
      uiValue = nextExpectedStage;
    }

    return NextResponse.json({ resp: respText, ui: uiValue, trip_plan: parsed?.trip_plan ?? null });
  } catch (error) {
    console.error("AI Route Error:", error);

    return NextResponse.json(
      {
        error: "Internal Server Error",
        details: error instanceof Error ? error.message : "Unknown error",
      },
      {
        status: 500,
      }
    );
  }
}